spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sanzhar_db
    username: sanzhar
    password: sanzhar
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
